theme = "soho"
baseurl = "/"
languageCode = "en"
title = "Tom Constant"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
summarylength = 10
enableEmoji = true

[params]
description = ""
# gravatar = "soho@example.com"
profilePicture = "images/profile.svg"
copyright = "Tom Constant"
license = "CC BY-SA 4.0"
licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"

  [[params.socialIcons]]
  icon = "fa-linkedin"
  title = "Linkedin"
  url = "http://www.linkedin.com/in/tomconstant"

  [[params.socialIcons]]
  icon = "fa-github"
  title = "GitHub"
  url = "http://github.com/tjconstant"

  [[params.socialIcons]]
  icon = "fa-twitter"
  title = "Twitter"
  url = "http://twitter.com/tomconstant"

[menu]

  [[menu.main]]
  name = "Posts"
  weight = 100
  identifier = "posts"
  url = "/posts/"

  [[menu.main]]
  name = "About"
  identifier = "about"
  weight = 300
  url = "/about/"

[markup]

  [markup.highlight]
  codeFences = true
  guessSyntax = false
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true
  style = "monokai"
  tabWidth = 4
